/**
 * Categories configuration for frontend use
 *
 * This file is auto-generated by scripts/generate-entry-points.js
 * DO NOT EDIT MANUALLY - Edit categories.config.js instead
 */

export interface Category {
  id: string;
  name: string;
  color: string;
  hoverColor: string;
}

export const CATEGORIES: Category[] = [
  {
    id: 'crypto',
    name: 'Crypto',
    color: '#059669',
    hoverColor: '#047857',
  },
  {
    id: 'ai',
    name: 'AI',
    color: '#8b5cf6',
    hoverColor: '#7c3aed',
  },
];

/**
 * Get category by ID
 */
export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((cat) => cat.id === id);
}

/**
 * Get all category IDs
 */
export function getCategoryIds(): string[] {
  return CATEGORIES.map((cat) => cat.id);
}
