/**
 * Configuration constants used throughout the application
 *
 * This file is auto-generated by scripts/generate-entry-points.js
 * DO NOT EDIT MANUALLY - Edit categories.config.js instead
 */

// Job Data Endpoints
export const ENDPOINTS = {
  CRYPTO_JOBS:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/crypto_jobs.json',
  CRYPTO_COMPANIES:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/crypto_companies.json',
  CRYPTO_CURRENT:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/crypto_current.json',
  CRYPTO_NEW_JOBS:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/crypto_jobs_new.json',
  AI_JOBS: 'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/ai_jobs.json',
  AI_COMPANIES:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/ai_companies.json',
  AI_CURRENT:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/ai_current.json',
  AI_NEW_JOBS:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/ai_jobs_new.json',
  FIN_JOBS:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/fin_jobs.json',
  FIN_COMPANIES:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/fin_companies.json',
  FIN_CURRENT:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/fin_current.json',
  FIN_NEW_JOBS:
    'https://raw.githubusercontent.com/crypto-jobs-fyi/crawler/refs/heads/main/fin_jobs_new.json',
} as const;

// LocalStorage Keys
export const STORAGE_KEYS = {
  FAVORITES: 'favoriteJobs',
  FILTERS: 'jobFilters',
  PREFERENCES: 'userPreferences',
  LAST_UPDATED: 'lastUpdated',
};

// UI Configuration
export const UI_CONFIG = {
  ITEMS_PER_PAGE: 50,
  TIMEOUT_MS: 15000,
  QUICK_FILTERS: {
    QA: ['QA', 'test', 'sdet', 'quality'],
    DEVOPS: ['DevOps', 'SRE', 'Reliability', 'Platform Engineering'],
  },
};

// Job Categories
export const JOB_CATEGORIES = {
  CRYPTO: 'crypto',
  AI: 'ai',
  FIN: 'fin',
} as const;

// Page Routes
export const ROUTES = {
  HOME: '/',
  CRYPTO_JOBS: '/crypto-jobs.html',
  CRYPTO_COMPANIES: '/crypto-companies.html',
  CRYPTO_NEW_JOBS: '/crypto-new-jobs.html',
  AI_JOBS: '/ai-jobs.html',
  AI_COMPANIES: '/ai-companies.html',
  AI_NEW_JOBS: '/ai-new-jobs.html',
  FIN_JOBS: '/fin-jobs.html',
  FIN_COMPANIES: '/fin-companies.html',
  FIN_NEW_JOBS: '/fin-new-jobs.html',
  FAVORITES: '/favorites.html',
  LOGIN: '/login.html',
  ACCOUNT: '/account.html',
  ADMIN: '/admin.html',
};

// Authentication Configuration
export const AUTH_CONFIG = {
  ENDPOINTS: {
    SEND_CODE: '/api/auth/send-code',
    VERIFY_CODE: '/api/auth/verify-code',
  },
  CODE_LENGTH: 4,
  CODE_EXPIRATION: 600, // 10 minutes in seconds
  SESSION_DURATION: {
    DEFAULT: 7 * 24 * 60 * 60 * 1000, // 7 days in milliseconds
    REMEMBER_ME: 30 * 24 * 60 * 60 * 1000, // 30 days in milliseconds
  },
  RATE_LIMIT: {
    MAX_ATTEMPTS: 3,
    WINDOW: 600, // 10 minutes in seconds
  },
} as const;
